Blog/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from . import views

#app_name告诉django这个urls属于哪个应用
#视图函数命令空间
app_name = 'Blog'

urlpatterns = [
    # url(r'^$', views.index, name='index'),
    #使用类视图的url写法
    url(r'^$', views.IndexView.as_view(), name='index'), #文章首页列表

    # url(r'^post/(?P<pk>[0-9]+)/$', views.detail, name='detail'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.PostDetailView.as_view(), name='detail'), #文章详情

    # url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.archives, name='archives'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.ArchivesView.as_view(), name='archives'), #文章归档

    # url(r'^category/(?P<pk>[0-9]+)/$', views.category, name='category'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.CategoryView.as_view(), name='category'), #文章分类

    url(r'^tag/(?P<pk>[0-9]+)/$', views.TagView.as_view(), name='tag'), #文章标签

    # url(r'^search/$', views.search, name='search'), #全文搜索
]

Comments/urls.py
from django.conf.urls import url

from . import  views

app_name = "Comments"

urlpatterns = [
    url(r'comment/post/(?P<post_pk>[0-9]+)/$', views.post_comment, name='post_comments'),
]

MySite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from Blog.feeds import AllPostRssFeed

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('Blog.urls')),
    url(r'', include('Comments.urls')),

    url(r'^all/rss/$', AllPostRssFeed(), name='rss'),  #配置rss订阅

    url(r'^search/', include('haystack.urls')), #配置引入haystack的urls
]

Blog/models.py
from django.db import models

from django.contrib.auth.models import User
from django.utils.six import python_2_unicode_compatible
from django.urls import reverse
import markdown
from django.utils.html import strip_tags
# Create your models here.


@python_2_unicode_compatible
class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

@python_2_unicode_compatible
class Tag(models.Model):
    name = models.CharField(max_length=100)
    def __str__(self):
        return self.name


@python_2_unicode_compatible
class Post(models.Model):
    #标题
    title = models.CharField(max_length=70)
    #正文
    body = models.TextField()
    #创建时间
    created_time = models.DateTimeField()
    #修改时间
    modified_time = models.DateTimeField()

    #文章摘要
    #默认字段不能为空， blank=TRUE 允许该字段可以为空
    excerpt = models.CharField(max_length=200, blank=True)
    #文章与分类属于一对多的关系，所有使用ForeignKey
    category = models.ForeignKey(Category)
    #文章与标签属于多对多的关系，所以使用ManyToManyField
    tags = models.ManyToManyField(Tag, blank=True)
    #文章作者，这里User是从django.contrib.auth.models 导入
    #django.contrib.auth 是django内置的应用，专门用于处理网用户的注册、登录等流程，User是django为
    #我们已经实现的用户模型
    #这里通过ForeignKey把文章和User关联起来
    #文章和作者是一对多的关系  和 category类似
    author = models.ForeignKey(User)

    #新增views字段记录阅读量
    views = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('Blog:detail', kwargs={'pk': self.pk})

    class Meta:
        ordering = ['-created_time']

    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])

    def save(self, *args, **kwargs):
        if not self.excerpt:
            md = markdown.Markdown(extensions=[
                'markdown.extensions.extra',
                'markdown.extensions.codehilite',
            ])

            self.excerpt = strip_tags(md.convert(self.body))[:100]
        super(Post, self).save(*args, **kwargs)

Comments/models.py
from django.db import models

# Create your models here.
from django.utils.six import python_2_unicode_compatible

class Comment(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=255)
    url = models.URLField(blank=True)
    text = models.TextField()
    created_time = models.DateTimeField(auto_now_add=True)

    post = models.ForeignKey("Blog.Post")

    def __str__(self):
        return self.text[:20]

Blog/views.py
from django.shortcuts import render
import markdown
# Create your views here.

from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView
from django.utils.text import slugify
from markdown.extensions.toc import TocExtension
from django.db.models import Q

from .models import Post, Category, Tag
from Comments.forms import CommentForm



################# 首页列表视图###################
# def index(request):
#     #return HttpResponse("欢迎您！！！")
#     post_list = Post.objects.all()
#     return render(request, 'Blog/index.html', context={
#                     'post_list': post_list
#     })


#使用List类视图
class IndexView(ListView):
    model = Post
    template_name = 'Blog/index.html'
    context_object_name = 'post_list'

    #通过paginate_by 属性来实现分页， 它的值代表每一页文章的数量
    paginate_by = 2    #指定每页显示两篇文章


    def get_context_data(self, **kwargs):
        '''
        在类视图中如果想给模板传递一个字典变量，则需要先通过get_context_data获得模板变量
        因此在这里复写get_context_data方法
        :param kwargs: 
        :return: 
        '''
        #先获取父类传递给模板的字典变量
        context = super().get_context_data(**kwargs)

        #其实在父类的字典变量中已经包含paginator、page_obj、is_paginated 这三个模板变量
        #其中paginator 是 Paginator 的一个实例，page_obj 是 Page 的一个实例，is_paginated 是一个布尔变量，用于指示是否已分页。
        paginator = context.get("paginator")
        page_obj = context.get("page_obj")
        is_paginated = context.get("is_paginated")

        #调用自定义的paginate_data方法获取分页所需数据
        paginate_data = self.paginate_data(paginator, page_obj, is_paginated)

        #将分页信息更新到context
        context.update(paginate_data)

        #将context内容返回
        return context

    def paginate_data(self, paginator, page_obj, is_paginated):
        '''
        自定义分页数据
        :param paginator: 
        :param page: 
        :param is_paginated: 
        :return: 
        '''
        if not is_paginated:
            #如果没有分页，就直接返回空{}
            return {}

        #当前分页左边连续的页码号
        left_page_num = []

        #当前分页左边连续的页码号
        right_page_num = []

        #标签第一页后是否显示省略号
        first_right_has = False

        # 标签第最后一页后是否显示省略号
        last_left_has = False

        #标记是否要显示第一页，如果当前页左边的连续页码中包含第一页，就不用在显示第一页
        show_first_page = False

        #原因同上
        show_last_page = False

        #获取当前请求的页号
        page_number = page_obj.number
        
        #获取分页后的总页数
        total_pages = paginator.num_pages

        #获得整个分页列表
        page_range = paginator.page_range

        if page_number == 1:
            #如果请求的当前页为1.那么当前页左边就不需要数据

            #如果只想获取当前页后的连续两页，如下
            right_page_num = page_range[page_number:page_number + 2]

            #如果最右边的页码比最后的页码减去1还要小，
            #说明右边的页码和最后一页的页之间还有其它页码，因此需要显示省略号
            if right_page_num[-1] < total_pages - 1:
                last_left_has = True

            if right_page_num[-1] < total_pages:
                show_last_page = True

        elif page_number == total_pages:

            left_page_num = page_range[(page_number -3) if (page_number - 3) > 0 else 0:page_number - 1]

            #如果最左侧页码大于2，则1号页和页码间有省略号
            if left_page_num[0] > 2:
                first_right_has = True

            #如果最左侧页码大于1，则需要显示1号页码
            if left_page_num[0] > 1:
                show_first_page = True
        else:
            left_page_num = page_range[(page_number -3) if (page_number -3) > 0 else 0:page_number - 1]
            right_page_num = page_range[page_number:page_number + 2]

            if right_page_num[-1] < total_pages - 1:
                last_left_has = True
            if right_page_num[-1] < total_pages:
                show_last_page = True

            if left_page_num[0] > 2:
                first_right_has = True
            if left_page_num[0] > 1:
                show_first_page = True

        data = {
            'left_page_num' : left_page_num,
            'right_page_num': right_page_num,
            'first_right_has': first_right_has,
            'last_left_has': last_left_has,
            'show_first_page': show_first_page,
            'show_last_page': show_last_page
        }

        return data


#####################归档视图##########################
# def archives(request, year, month):
#     '''
#     根据日期获取归档文件
#     :param request:
#     :param year:
#     :param month:
#     :return:
#     '''
#     post_list = Post.objects.all().filter(created_time__year=year,
#                                           created_time__month=month)
#     return render(request, 'Blog/index.html', context={'post_list': post_list})


class ArchivesView(ListView):
    model = Post
    template_name = "Blog/index.html"
    context_object_name = "post_list"

    def get_queryset(self):
        year = self.kwargs.get("year")
        month = self.kwargs.get("month")

        return super(ArchivesView, self).get_queryset().filter(created_time__year=year,
                                                        created_time__month=month)


########################文章分类视图#########################

# def category(request, pk):
#     #注册Category类
#     cate = get_object_or_404(Category, pk=pk)
#     post_list = Post.objects.all().filter(category=cate)
#     return render(request, 'Blog/index.html', context={'post_list': post_list})


class CategoryView(ListView):
    model = Post
    template_name = "Blog/index.html"
    context_object_name = "post_list"

    def get_queryset(self):
        cate = get_object_or_404(Category, pk = self.kwargs.get('pk'))
        return super(CategoryView, self).get_queryset().filter(category = cate)


############################文章标签试图##################################
class TagView(ListView):
    model = Post
    template_name = "Blog/index.html"
    context_object_name = "post_list"

    def get_queryset(self):
        tag = get_object_or_404(Tag, pk = self.kwargs.get("pk"))
        return super(TagView, self).get_queryset().filter(tags = tag)

############################文章详情视图###############################

# def detail(request, pk):
#     post = get_object_or_404(Post, pk=pk)
#
#     #阅读量增加1
#     post.increase_views()
#
#     post.body = markdown.markdown(post.body,
#                                   extensions=[
#                                       'markdown.extensions.extra',
#                                       'markdown.extensions.codehilite',
#                                       'markdown.extensions.toc',
#                                   ]
#                          )
#
#     form = CommentForm()
#     comment_list = post.comment_set.all()
#
#     context = {'post':post,
#                'form': form,
#                'comment_list': comment_list
#                }
#
#
#     return render(request, 'Blog/detail.html', context= context)

class PostDetailView(DetailView):
    model = Post
    template_name = "Blog/detail.html"
    context_object_name = "post"


    def get(self, request, *args, **kwargs):
        #get方法会返回一个HttpResponse实例
        #只有先调用父类的get方法，能够有self.object属性，其值为Post模型实例
        #即被访问的文章post
        response = super(PostDetailView, self).get(request, *args, **kwargs)

        #将文章阅读量加1
        self.object.increase_views()

        return response


    def get_object(self, queryset=None):
        #重写get_object 方法的目的是需要对post的body值进行渲染
        post = super(PostDetailView, self).get_object(queryset=None)
        # post.body = markdown.markdown(post.body,
        #                               extensions =[
        #                                   'markdown.extensions.extra',
        #                                   'markdown.extensions.codehilite',
        #                                   'markdown.extensions.toc',
        #                               ])
        md = markdown.Markdown(extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            # 'markdown.extensions.toc',
            TocExtension(slugify=slugify)
        ])
        post.body = md.convert(post.body)
        post.toc = md.toc
        return post



    def get_context_data(self, **kwargs):

        context = super(PostDetailView, self).get_context_data(**kwargs)
        form = CommentForm()
        comment_list = self.object.comment_set.all()
        context.update({
            'form': form,
            'comment_list': comment_list
        }
        )

        return context


def search(request):
    q = request.GET.get('query')
    error_msg = ''

    if not q:
        error_msg = "请输入关键词"
        return render(request, 'Blog/index.html', {'error_msg': error_msg})

    post_list = Post.objects.filter(Q(title__icontains=q) | Q(body__icontains=q))
    return render(request, 'Blog/index.html', {"error_msg": error_msg,
                                               "post_list": post_list})

templates/Blog/detail.html
{% extends "base.html" %}

{% block main %}
    <article class="post-{{ post.pk }}">
                    <header class="entry-header">
                        <h1 class="entry-title">{{ post.title }}</h1>
                        <div class="entry-meta">
                            <span class="post-category"><a href="{% url "Blog:category" post.category.pk %}">{{ post.category.name }}</a></span>
                            <span class="post-date"><a href="#"><time class="entry-date"
                                                                      datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
                            <span class="post-author"><a href="#">{{ post.auther }}</a></span>
                            <span class="comments-link"><a href="#">{{ post.comment_set.count }} 评论</a></span>
                            <span class="views-count"><a href="#">{{ post.views }} 阅读</a></span>
                        </div>
                    </header>
                    <div class="entry-content clearfix">
                        {{ post.body|safe }}
                    </div>
                </article>
    <section class="comment-area" id="comment-area">
                    <hr>
                    <h3>发表评论</h3>
                    <form action="{% url "Comments:post_comments" post.pk %}" method="post" class="comment-form">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-4">
                                <label for="{{ form.name.id_for_label }}">名字：</label>
                                {{ form.name }}
                                {{ form.name.errors }}
                            </div>
                            <div class="col-md-4">
                                <label for="{{ form.email.id_for_label }}">邮箱：</label>
                                {{ form.email }}
                                {{ form.email.errors }}
                            </div>
                            <div class="col-md-4">
                                <label for="{{ form.url.id_for_label }}">网址：</label>
                                {{ form.url }}
                                {{ form.url.errors }}
                            </div>
                            <div class="col-md-12">
                                <label for="{{ form.text.id_for_label }}">评论：</label>
                                {{ form.text }}
                                {{ form.text.errors }}
                                <button type="submit" class="comment-btn">发表</button>
                            </div>
                        </div>    <!-- row -->
                    </form>
                    <div class="comment-list-panel">
                        <h3>评论列表，共 <span>{{ post.comment_set.count }}</span> 条评论</h3>
                        <ul class="comment-list list-unstyled">
                            {% for comment in comment_list %}
                            <li class="comment-item">
                                <span class="nickname">{{ comment.name }}</span>
                                <time class="submit-date" datetime="{{ comment.created_time }}">{{ comment.created_time }}</time>
                                <div class="text">
                                  {{ comment.text }}
                                </div>
                            </li>
                                {% empty %}
                                暂无评论
                           {% endfor %}
                        </ul>
                    </div>
                </section>
{% endblock main %}

{% block top %}
    <div class="widget widget-content">
                    <h3 class="widget-title">文章目录</h3>
                    {{ post.toc | safe }}
                </div>
{% endblock top %}

templates/Blog/index.html
{% extends "base.html" %}

{% block main %}
    {% if error_msg %}
        <p>{{ error_msg }}</p>
    {% endif %}
  {% for post in post_list %}
                <article class="post post-{{ post.pk }}">
                    <header class="entry-header">
                        <h1 class="entry-title">
                            <a href={{ post.get_absolute_url }}>{{ post.title }}</a>
                        </h1>
                        <div class="entry-meta">
                            <span class="post-category"><a href="{% url "Blog:category" post.category.pk %}">{{ post.category.name }}</a></span>
                            <span class="post-date"><a href="#"><time class="entry-date"
                                                                      datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
                            <span class="post-author"><a href="#">{{ post.author }}</a></span>
                            <span class="comments-link"><a href="#">{{ post.comment_set.count }} 评论</a></span>
                            <span class="views-count"><a href="{{ post.get_absolute_url }}">{{ post.views }} 阅读</a></span>
                        </div>
                    </header>
                    <div class="entry-content clearfix">
                        <p>{{ post.excerpt }} ...</p>
                        <div class="read-more cl-effect-14">
                            <a href="{{ post.get_absolute_url }}" class="more-link">继续阅读<span class="meta-nav">→</span></a>
                        </div>
                    </div>
                </article>
                    {% empty %}
                    <div class="no-post">
                      暂时没有发表文章
                    </div>
                {% endfor %}

                 <!---------实现分页功能   ---------------------------->
                 <!----------简易版---------------------------------->
{#                 {% if is_paginated %}#}
{#                     <div class="pagination-simple">#}
{#                     {% if page_obj.has_previous %}#}
{#                         <a href="?page={{ page_obj.previous_page_number }}">上一页</a>#}
{#                     {% endif %}#}
{#                         <span class="current">第 {{ page_obj.number }}页 / 共 {{ paginator.num_pages }}页</span>#}
{#                     {% if page_obj.has_next %}#}
{#                         <a href="?page={{ page_obj.next_page_number }}">下一页</a>#}
{#                     {% endif %}#}
{#                     </div>#}
{#                 {% endif %}#}

                      <!----------实用版---------------------------------->
                  {% if is_paginated %}
                      <div class="pagination">
                      {% if show_first_page %}
                          <a href="?page=1">1</a>
                      {% endif %}

                      {% if left_page_num %}
                          {% if first_right_has %}
                              <span>...</span>
                          {% endif %}
                          {% for i in  left_page_num %}
                              <a href="?page={{ i }}">{{ i }}</a>
                          {% endfor %}
                      {% endif %}

                      <a href="?page={{ page_obj.number }}" style="color: red">{{ page_obj.number }}</a>

                      {% if right_page_num %}
                          {% for i in right_page_num %}
                              <a href="?page={{ i }}">{{ i }}</a>
                          {% endfor %}
                          {% if last_left_has %}
                              <span>...</span>
                          {% endif %}
                      {% endif %}

                      {% if show_last_page %}
                          <a href="?page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a>
                      {% endif %}

                      </div>
                  {% endif %}


{% endblock main %}